### ISSUE TITLE
希望大佬优化一下 

### ISSUE THREAD

**Issue by iptodays** [zangqilong198812/GithubAddictFeedback#23]
大佬。设置里面的分享给好友用的是activityvc。但是点击之后。分享视图出来的太慢了。我这边测试发现。当activityvc走到viewdidload方法的时候 视图刚好出现。这个可以改一下吗。加个等待动画啥的

**Comment by zangqilong198812** [comment]
建议使用正式版。TestFlight 早就不更新了。
