### ISSUE TITLE
issue图片显示问题

### ISSUE THREAD

**Issue by kayanouriko** [zangqilong198812/GithubAddictFeedback#25]
issue里面的图片显示是原始分辨率的，导致大于手机屏幕的图片会显示不全

**Comment by zangqilong198812** [comment]
能否给我一个链接

**Comment by kayanouriko** [comment]
例如：https://github.com/LoveLiveSunshine/pixiv.moe/issues/7 
而且有些issue点击的时候卡主了，花了一阵子才进去，可能是点击的时候做了一些请求卡主线程了

**Comment by kayanouriko** [comment]
还有就是时间线点击头像和profile会偶尔随机闪退

**Comment by zangqilong198812** [comment]
感谢反馈，我在crashlytics上查一下。

**Comment by zangqilong198812** [comment]
点击头像crash问题已经修复。
